name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: keda
          MONGO_INITDB_ROOT_PASSWORD: keda_admin_2024
        options: >-
          --replSet rs0
          --bind_ip_all
          --auth
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # 初始化 replica set（因为你的连接串里有 replicaSet=rs0）
      - name: Init Mongo ReplicaSet
        run: |
          mongosh --host localhost --port 27017 -u keda -p keda_admin_2024 --authenticationDatabase admin <<EOF
          rs.initiate({
            _id: "rs0",
            members: [{ _id: 0, host: "localhost:27017" }]
          })
          EOF

      - name: Test
        env:
          Mongo__ConnectionString: "mongodb://keda:keda_admin_2024@localhost:27017/StationConfiguration/?authSource=admin&replicaSet=rs0&authMechanism=SCRAM-SHA-256&readPreference=primary&directConnection=true"
        run: dotnet test --no-build --verbosity normal

      # Stryker
      - name: Install Stryker
        run: |
          dotnet tool install -g dotnet-stryker
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Stryker
        run: dotnet stryker --config-file KEDA_Share.Test/stryker-config.json
